# Generated by Django 2.2 on 2020-09-21 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('localizacao', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='galeria/thumbnail')),
            ],
            options={
                'ordering': ('data',),
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='galeria/imagens')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Album')),
            ],
        ),
    ]
