# Generated by Django 2.2 on 2020-09-22 11:05

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.album_directory_path),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.imagem_directory_path),
        ),
    ]
