# Generated by Django 2.2 on 2020-09-29 19:52

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200922_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Álbum', 'verbose_name_plural': 'Álbuns'},
        ),
        migrations.AlterModelOptions(
            name='imagem',
            options={'verbose_name': 'Imagem', 'verbose_name_plural': 'Imagens'},
        ),
        migrations.AlterField(
            model_name='album',
            name='data',
            field=models.DateField(verbose_name='Data do evento'),
        ),
        migrations.AlterField(
            model_name='album',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do evento'),
        ),
        migrations.AlterField(
            model_name='album',
            name='localizacao',
            field=models.CharField(max_length=100, verbose_name='Localização do evento'),
        ),
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.album_directory_path, verbose_name='Cartaz do evento'),
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título do evento'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Album', verbose_name='A qual álbum se refere'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título da imagem'),
        ),
    ]
