# Generated by Django 2.2 on 2021-03-10 01:34

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200929_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='album',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='album',
            name='localizacao',
            field=models.CharField(max_length=100, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.album_directory_path, verbose_name='Thumbnail do álbum'),
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
